config/routes.rb
Rails.application.routes.draw do
  root to: "top#index"
  devise_for :users

  post 'items/new', to: 'items#create'
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end

    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      post 'pay', to: 'items#pay'
      get 'buy', to:'items#buy'
      get 'purchase', to:'items#purchase'
    end
  end
  resources :credits, only: [:new, :show] do
    collection do
      post 'show', to: 'credits#show'
      post 'pay', to: 'credits#pay'
      post 'delete', to: 'credits#delete'
    end
  end
  resources :mypage
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_ancestry
end

app/models/condition.rb
class Condition  < ActiveHash::Base
  self.data = [
      {id: 1, name: '新品、未使用'}, {id: 2, name: '未使用に近い'},
      {id: 3, name: '目立った傷や汚れなし'}, {id: 4, name: 'やや傷や汚れあり'}, {id: 5, name: '傷や汚れあり'},
      {id: 6, name: '全体的に状態が悪い'}
  ]
end

app/models/condition_ls.rb
class Condition_ls < ActiveHash::Base
  self.data = [
      {id: 1, name: '新品、未使用'}, {id: 2, name: '未使用に近い'},
      {id: 3, name: '目立った傷や汚れなし'}, {id: 4, name: 'やや傷や汚れあり'}, {id: 5, name: '傷や汚れあり'},
      {id: 6, name: '全体的に状態が悪い'}
  ]
end

app/models/conditionls.rb
class Conditionls < ActiveHash::Base
  self.data = [
      {id: 1, name: '新品、未使用'}, {id: 2, name: '未使用に近い'},
      {id: 3, name: '目立った傷や汚れなし'}, {id: 4, name: 'やや傷や汚れあり'}, {id: 5, name: '傷や汚れあり'},
      {id: 6, name: '全体的に状態が悪い'}
  ]
end

app/models/country.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :user
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  has_many :users, through: :evalutaions_users
  has_many :items
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image_url, ImageUploader
  belongs_to :item, optional: true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :user, presence: true
  validates :seller_id, presence: true
  validates :category_id, presence: true, exclusion: { in: [0,1,2,6,9,10,14]}
  validates :postage_id, presence: true
  validates :condition_id, presence: true
  validates :shipping_day_id, presence: true
  validates :shippingpayer_id, presence: true
  validates :images, presence: true
  validates :price, presence: true
  belongs_to :user
  belongs_to :category
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to_active_hash :condition
    belongs_to_active_hash :shippingpayer
    belongs_to_active_hash :prefecture
    belongs_to_active_hash :shipping_day
    belongs_to_active_hash :status
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
end

app/models/postage.rb
class Postage < ApplicationRecord
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/shipping_day.rb
class ShippingDay < ActiveHash::Base
  self.data = [
      {id: 1, name: '1~2日で発送'}, {id: 2, name: '2~3日で発送'},
      {id: 3, name: '3~4日で発送'}
  ]
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
      {id: 1, name: '出品中'}, {id: 2, name: '取引中'},
      {id: 3, name: '売約済み'}
  ]
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one :place
  has_many :items
  has_many :goods
  has_many :evaluations, through: :evalutaions_users
  has_many :credits
 

  validates :nickname, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: { minimum: 7 }, confirmation: true
  VALID_NAME_REGEX = /\A^[ぁ-んァ-ヶー一-龠]+$\z/
  validates :last_name, presence: true, format: { with: VALID_NAME_REGEX }
  VALID_NAME_REGEX = /\A^[ぁ-んァ-ヶー一-龠]+$\z/
  validates :first_name, presence: true, format: { with: VALID_NAME_REGEX }
  VALID_KANA_NAME_REGEX = /\A^[ア-ン゛゜ァ-ォャ-ョー「」、]+\z/
  validates :kana_last_name, presence: true, format: { with: VALID_KANA_NAME_REGEX }
  VALID_KANA_NAME_REGEX = /\A^[ア-ン゛゜ァ-ォャ-ョー「」、]+\z/
  validates :kana_first_name, presence: true, format: { with: VALID_KANA_NAME_REGEX }
  validates :birth_date, presence: true

end

app/helpers/sell_helper.rb
module SellHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/_error_messages.html.haml
-if model.errors.any? 
  .alert
    %ul
      -model.errors.full_messages.each do |message| 
        %li= message

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title FreemarketSample64a
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .contents
      = render 'layouts/notifications'
      = yield

app/views/temple/_exhibitionbtn.html.haml
.btn
  .btn_text
    出品する
    .btn_icon
      - if user_signed_in?
        = link_to new_item_path do
          = image_tag "icon_camera.png"
      - else 
        = link_to new_user_registration_path do
          = image_tag "icon_camera.png"

app/views/temple/_footer.html.haml
.footer
  .footer_banner
    .banner
      .banner_h1
        だれでもかんたん、人生を変えるフリマアプリ
      .banner_h2
        今すぐ無料ダウンロード！
      .banner_icon
        .logoA
          = image_tag "Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg", size: "170x66", alt: "app"
        .logoB
          = image_tag "Google_Play_Store_badge_EN.svg", size: "190x68", alt: "googlepray"
.footer_text
  .footer_text_contents
    %li.information
      .information_top 
        FURIMAについて
      %ul.footer_lists
        %li<
          会社概要（運営会社）
        %li<
          プライバシーポリシー
        %li<
          FURIMA利用規約
        %li<
          ポイントに関する特約
    %li.information
      .information_top 
        FURIMAを見る
      %ul.footer_lists
        %li<
          カテゴリー一覧
        %li<
          ブランド一覧
    %li.information
      .information_top 
        ヘルプ＆ガイド
      %ul.footer_lists
        %li<
          FURIMAガイド
        %li<
          FURIMAロゴ利用ガイドライン
        %li<
          お知らせ
  .footer_logo
    = image_tag "logo-white.png", size: "140x40", alt: "test",class: "logo"
    ©︎FURIMA

app/views/temple/_header.html.haml
.header
  .header_main
    .header_main_logo
      = image_tag "logo.png", size: "140x40", alt: "test",class: "logo"
    .header_main_category
    .header_main_brand
    .header_main_search
      %input.search__input{:placeholder => "キーワードから探す", :type => "text"}/
      .icon
        = icon('fas', 'search')
  .header_contents
    .header_contents_left
      .category
        %ul.gnav
          %li
            = link_to "#"  do
              カテゴリー
              %ul
                - @categories.each do |category1|
                  %li
                    = link_to "#"  do
                      = category1.name
                      %ul
                        - category1.children.each do |category2|
                          %li
                            = link_to "#"  do
                              = category2.name
                              %ul
                                - category2.children.each do |category3|
                                  %li
                                    = link_to "#"  do
                                      = category3.name
      .brand
        ブランド
    .header_contents_right
      .signin
        - if user_signed_in?
          = link_to "マイページ", mypage_index_path, class: "new"
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "new"
        - else
          = link_to "ログイン", new_user_session_path, class: "new"
          = link_to "新規登録", new_user_registration_path, class: "new"

    
    