config/routes.rb
Rails.application.routes.draw do
  root to: "top#index"
  devise_for :users

  post 'items/new', to: 'items#create'
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end

    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      post 'pay', to: 'items#pay'
      get 'buy', to:'items#buy'
      get 'purchase', to:'items#purchase'
    end
  end
  resources :credits, only: [:new, :show] do
    collection do
      post 'show', to: 'credits#show'
      post 'pay', to: 'credits#pay'
      post 'delete', to: 'credits#delete'
    end
  end
  resources :mypage
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :user, presence: true
  validates :seller_id, presence: true
  validates :category_id, presence: true, exclusion: { in: [0,1,2,6,9,10,14]}
  validates :postage_id, presence: true
  validates :condition_id, presence: true
  validates :shipping_day_id, presence: true
  validates :shippingpayer_id, presence: true
  validates :images, presence: true
  validates :price, presence: true
  belongs_to :user
  belongs_to :category
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to_active_hash :condition
    belongs_to_active_hash :shippingpayer
    belongs_to_active_hash :prefecture
    belongs_to_active_hash :shipping_day
    belongs_to_active_hash :status
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show,:edit, :update, :destroy, :pay, :buy,:purchase] 
  before_action :set_categories, only: [:new, :show,:purchase]
  before_action :set_card, only: [:pay,:purchase]

  def index
  end
  
  def new
    @category_parent_array = Category.where(ancestry: nil).pluck(:id,:name)
    @item = Item.new
    @item.images.new
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      @item.images.new
      render :new
    end
  end

  def get_category_children
    respond_to do |format|
      format.html
      format.json do
        @children = Category.find(params[:parent_id]).children
      end
    end
  end
  
  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end
  
  def search
      redirect_to root_path
  end

  def purchase
    @parents = @item.category.parent
    @category = @parents.parent
    if @card.blank?
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def show
    @parents = @item.category.parent
    @category = @parents.parent
    @user = @item.user
  end

  def destroy
    if @item.destroy
      redirect_to root_path, notice: "削除が完了しました"
    else
      redirect_to root_path, alert: "削除が失敗しました"
    end
  end

  def buy
    @item.update(buyer_params)
    if @item.save
      redirect_to root_path, notice: "購入しました"
    else
      redirect_to root_path, alert: "購入に失敗しました"
    end
  end

  def pay
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    Payjp::Charge.create(
      amount: @item.price,
      customer: @card.customer_id,
      currency: 'jpy',
    )
    redirect_to action: "buy"
  end

  def edit    
    grandchild_category = @item.category
    child_category = grandchild_category.parent

    @category_parent_array = Category.where(ancestry: nil).pluck(:id, :name)
    @category_children_array = Category.where(ancestry: child_category.ancestry)
    @category_grandchildren_array = Category.where(ancestry: grandchild_category.ancestry)
  end
  
  def update
    if @item.update(item_params)
      redirect_to root_path, notice: '更新が完了しました。'
    else
      redirect_to edit_item_path, notice: '更新に失敗しました。全ての項目に記述して下さい。'
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :description, :category_id, :condition_id, :shippingpayer_id, :postage_id, :shipping_day_id, :price, images_attributes: [:image_url, :_destroy, :id]).merge(user_id: current_user.id).merge(seller_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_categories
    @categories = Category.where(ancestry: nil)
  end

  def set_card
    @card = Credit.find_by(user_id: current_user.id)
  end

  def buyer_params
    params.permit().merge(buyer_id: current_user.id)
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_new.html.haml
%body
  .sell-header
    %a
      = image_tag "logo.png", size: "185x49", alt: "logo"
  .main
    = form_for (@item),url: '/items/new' , builder: CustomFormHelper, class: "select" do |f|
      .block
        .formGroup
          .formLabel
            %label
              出品画像
            %span.tag.must
              必須
          .subtitle
            最大5枚までアップできます。
          .post__drop__box__container
            .prev-content
            .label-content
              %label{for: "item_images_attributes_0_image_url", class: "label-box", id: "label-box--0"}
                %pre.label-box__text-visible クリックしてファイルをアップロード
            .hidden-content
              = f.fields_for :images ,multiple: true do |i|
                = f.error_message_on(:images, Item.human_attribute_name('images'))
                = i.file_field :image_url, class: "hidden-field"
                %input{class:"hidden-field", type: "file", name: "item[images_attributes][1][image_url]", id: "item_images_attributes_1_image_url" }
                %input{class:"hidden-field", type: "file", name: "item[images_attributes][2][image_url]", id: "item_images_attributes_2_image_url" }
                %input{class:"hidden-field", type: "file", name: "item[images_attributes][3][image_url]", id: "item_images_attributes_3_image_url" }
                %input{class:"hidden-field", type: "file", name: "item[images_attributes][4][image_url]", id: "item_images_attributes_4_image_url" }
      %hr
      .block
        .formGroup
          .formLabel
            %label
              商品名
            %span.tag.must
              必須
          .input-area
            = f.text_field :name, {class: "input-area", placeholder: "40字まで", type: "text", maxlength: "40"}

        .formGroup
          .formLabel
            %label
              商品の説明
            %span.tag.must
              必須
          .text-area
            = f.text_area :description, {class: "text-area", placeholder: "商品の説明を入力してください", maxlength: "1000"}
        .item-info__footer
          %span 
      %hr
      .block
        %p.title
          商品の詳細
        .formGroup
          .style
            .formLabel
              %label
                カテゴリー
              %span.tag.must
                必須
            .select#select
              = f.collection_select :category_id, Category.where(ancestry: nil),:id, :name,{prompt: "選択してください"}, {class: 'select-default', id: 'parent-form'}
              = f.error_message_on(:category_id, Item.human_attribute_name('category_id'))
              %svg{width: "24", height: "24", viewBox: "0 0 24 24"}
                %path{d: "M12,15.66a1.73,1.73,0,0,1-1.2-.49L5.21,9.54a.7.7,0,0,1,1-1l5.62,5.62c.15.15.27.15.41,0L17.8,8.6a.71.71,0,0,1,1,0,.69.69,0,0,1,0,1l-5.57,5.58A1.71,1.71,0,0,1,12,15.66Z"}
       
        .formGroup
          .formLabel
            %label
              ブランド
            %span.tag.option
              任意
          %input.input-area{name: "brand",placeholder: "例）シャネル", type: "text"}  
        .formGroup
          .formLabel
            %label
              商品の状態
            %span.tag.must
              必須
          .select
            = f.collection_select :condition_id, Conditionls.all, :id, :name, prompt: "選択して下さい", required: true
            = f.error_message_on(:condition_id, Item.human_attribute_name('condition_id'))
            %svg{width: "24", height: "24", viewBox: "0 0 24 24"}
              %path{d: "M12,15.66a1.73,1.73,0,0,1-1.2-.49L5.21,9.54a.7.7,0,0,1,1-1l5.62,5.62c.15.15.27.15.41,0L17.8,8.6a.71.71,0,0,1,1,0,.69.69,0,0,1,0,1l-5.57,5.58A1.71,1.71,0,0,1,12,15.66Z"}
      %hr
      .block
        %p.title
          配送について
        .formGroup
          .formLabel
            %label
              配送料の負担
            %span.tag.must
              必須
          .select
            = f.collection_select :shippingpayer_id, Shippingpayer.all, :id, :name, prompt: "選択して下さい", required: true
            = f.error_message_on(:shippingpayer_id, Item.human_attribute_name('shippingpayer_id'))
            %svg{width: "24", height: "24", viewBox: "0 0 24 24"}
              %path{d: "M12,15.66a1.73,1.73,0,0,1-1.2-.49L5.21,9.54a.7.7,0,0,1,1-1l5.62,5.62c.15.15.27.15.41,0L17.8,8.6a.71.71,0,0,1,1,0,.69.69,0,0,1,0,1l-5.57,5.58A1.71,1.71,0,0,1,12,15.66Z"}
        .formGroup
          .formLabel
            %label
              配送元の地域
            %span.tag.must
              必須
          .select
            = f.collection_select :postage_id, Prefecture.all, :id, :name, prompt: "選択して下さい"
            = f.error_message_on(:postage_id, Item.human_attribute_name('postage_id'))
            %svg{width: "24", height: "24", viewBox: "0 0 24 24"}
              %path{d: "M12,15.66a1.73,1.73,0,0,1-1.2-.49L5.21,9.54a.7.7,0,0,1,1-1l5.62,5.62c.15.15.27.15.41,0L17.8,8.6a.71.71,0,0,1,1,0,.69.69,0,0,1,0,1l-5.57,5.58A1.71,1.71,0,0,1,12,15.66Z"}
        .formGroup
          .formLabel
            %label
              配送までの日数
            %span.tag.must
              必須
          .select
            = f.collection_select :shipping_day_id, ShippingDay.all, :id, :name, prompt: "選択して下さい"
            = f.error_message_on(:shipping_day_id, Item.human_attribute_name('shipping_day_id'))
            %svg{width: "24", height: "24", viewBox: "0 0 24 24"}
              %path{d: "M12,15.66a1.73,1.73,0,0,1-1.2-.49L5.21,9.54a.7.7,0,0,1,1-1l5.62,5.62c.15.15.27.15.41,0L17.8,8.6a.71.71,0,0,1,1,0,.69.69,0,0,1,0,1l-5.57,5.58A1.71,1.71,0,0,1,12,15.66Z"}
      %hr
      .block
        %p.title
          価格（¥300~9,999,999)
        .formGroup
          .price
            .result-price
              .formLabel.price-label
                %label
                  販売価格
                %span.tag.must.tag-price
                  必須
              %p.yen
                ¥
              .input-price
                = f.text_field :price
            .result-price
              販売手数料 (10%)
            %hr
            .result-price
              販売利益
          .pushbutton
            %button{type: "submit", class: 'submit button'}
              出品する
            %a.return.button{href: "/"}
              もどる
          %p.caution
            禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。

app/views/items/edit.html.haml
%body
  .sell-header
    %a
      = image_tag "logo.png", size: "185x49", alt: "logo"

  .main
    = form_for (@item), builder: CustomFormHelper, class: "select" do |f|
      = render 'layouts/error_messages', model: f.object
      .block
        .formGroup
          .formLabel
            %label
              出品画像
              %span.tag.must 
                必須
          .subtitle
            最大5枚までアップロードできます
          .post__drop__box__container
            .prev-content
              //JSで挿入したhtmlと同じ形 each文でのプレビュー表示
              - @item.images.each_with_index do |image,i|
                -if image.persisted?
                  .preview-box
                    .upper-box
                      = image_tag image.image_url, width: "112", height: "112", alt: "preview"
                    .lower-box
                      .delete-box
                        .delete-btn{data:{delete_id: i}}削除
            .label-content
              //プレビューの数に合わせてforオプションを指定
              = f.label :"images_attributes_#{@item.images.length}_image_url", class: "label-box", id: "label-box--#{@item.images.length}" do
                %pre.label-box__text-visible クリックしてファイルをアップロード
            .hidden-content
              = f.fields_for :images do |i|
                //プレビューが出ている分のfile_fieldとdelete用のチェックボックスを設置
                = i.file_field :image_url, class: "hidden-field"
                - if i.object.persisted?
                  = i.check_box:_destroy, class: "hidden-checkbox"
              //5つのfile_fieldを準備するに当たって、足りない分を表示
              - @item.images.length.upto(4) do |i|
                %input{name: "item[images_attributes][#{i}][image_url]", id: "item_images_attributes_#{i}_image_url", class:"hidden-field", type:"file"}
      %hr
      .block
        .formGroup
          .formLabel
            %label
              商品名
            %span.tag.must
              必須
          .input-area
            = f.text_field :name, {class: "input-area", placeholder: "40字まで", type: "text", maxlength: "40"}
        .formGroup
          .formLabel
            %label
              商品の説明
            %span.tag.must
              必須
          .text-area
            = f.text_area :description, {class: "text-area", placeholder: "商品の説明を入力してください", maxlength: "1000"}
        .item-info__footer
          %span 

      %hr
      .block
        %p.title
          商品の詳細
        .formGroup
          .style
            .formLabel
              %label
                カテゴリー
              %span.tag.must
                必須
            - if @item.category_id.blank?  
              .select#select
                = f.collection_select :category_id, Category.where(ancestry: nil),:id, :name,{prompt: "選択してyo"}, {class: 'select-default', id: 'parent-form'}
                = f.error_message_on(:category_id, Item.human_attribute_name('category_id'))
                %svg{width: "24", height: "24", viewBox: "0 0 24 24"}
                  %path{d: "M12,15.66a1.73,1.73,0,0,1-1.2-.49L5.21,9.54a.7.7,0,0,1,1-1l5.62,5.62c.15.15.27.15.41,0L17.8,8.6a.71.71,0,0,1,1,0,.69.69,0,0,1,0,1l-5.57,5.58A1.71,1.71,0,0,1,12,15.66Z"}
            - else
              .select#select
                = f.collection_select :category_id, Category.where(ancestry: nil), :id, :name, {selected:@item.category.parent().parent().id}, {class: 'select-default', id: 'parent-form'}
                %svg{width: "24", height: "24", viewBox: "0 0 24 24"}
                  %path{d: "M12,15.66a1.73,1.73,0,0,1-1.2-.49L5.21,9.54a.7.7,0,0,1,1-1l5.62,5.62c.15.15.27.15.41,0L17.8,8.6a.71.71,0,0,1,1,0,.69.69,0,0,1,0,1l-5.57,5.58A1.71,1.71,0,0,1,12,15.66Z"}
              .select#select
                = f.select :category_id, options_for_select(@category_children_array.map{|b| [b.name, b.id, {data:{category: b.id}}]}, {selected: @item.category.parent().id}),{}, {class: 'category-wrapper__category form-control', id: 'child_category'}
                %svg{width: "24", height: "24", viewBox: "0 0 24 24"}
                  %path{d: "M12,15.66a1.73,1.73,0,0,1-1.2-.49L5.21,9.54a.7.7,0,0,1,1-1l5.62,5.62c.15.15.27.15.41,0L17.8,8.6a.71.71,0,0,1,1,0,.69.69,0,0,1,0,1l-5.57,5.58A1.71,1.71,0,0,1,12,15.66Z"}
              .select#select 
                = f.select :category_id, options_for_select(@category_grandchildren_array.map{|b| [b.name, b.id, {data:{category: b.id}}]}, {selected: @item.category_id}),{}, {class: 'category-wrapper__category form-control', id: 'grandchild_category'}
                = f.error_message_on(:category_id, Item.human_attribute_name('category_id'))
                %svg{width: "24", height: "24", viewBox: "0 0 24 24"}
                  %path{d: "M12,15.66a1.73,1.73,0,0,1-1.2-.49L5.21,9.54a.7.7,0,0,1,1-1l5.62,5.62c.15.15.27.15.41,0L17.8,8.6a.71.71,0,0,1,1,0,.69.69,0,0,1,0,1l-5.57,5.58A1.71,1.71,0,0,1,12,15.66Z"}
        .formGroup
          .formLabel
            %label
              ブランド
            %span.tag.option
              任意
          .input-area
            %input.input-area{name: "brand",placeholder: "例）シャネル", type: "text"}  
        .formGroup
          .formLabel
            %label
              商品の状態
            %span.tag.must
              必須
          .select
            = f.collection_select :condition_id, Conditionls.all, :id, :name, prompt: "選択して下さい"
            %svg{width: "24", height: "24", viewBox: "0 0 24 24"}
              %path{d: "M12,15.66a1.73,1.73,0,0,1-1.2-.49L5.21,9.54a.7.7,0,0,1,1-1l5.62,5.62c.15.15.27.15.41,0L17.8,8.6a.71.71,0,0,1,1,0,.69.69,0,0,1,0,1l-5.57,5.58A1.71,1.71,0,0,1,12,15.66Z"}
      %hr
      .block
        %p.title
          配送について
        .formGroup
          .formLabel
            %label
              配送料の負担
            %span.tag.must
              必須
          .select
            = f.collection_select :shippingpayer_id, Shippingpayer.all, :id, :name, prompt: "選択して下さい"
            %svg{width: "24", height: "24", viewBox: "0 0 24 24"}
              %path{d: "M12,15.66a1.73,1.73,0,0,1-1.2-.49L5.21,9.54a.7.7,0,0,1,1-1l5.62,5.62c.15.15.27.15.41,0L17.8,8.6a.71.71,0,0,1,1,0,.69.69,0,0,1,0,1l-5.57,5.58A1.71,1.71,0,0,1,12,15.66Z"}
        .formGroup
          .formLabel
            %label
              配送元の地域
            %span.tag.must
              必須
          .select
            = f.collection_select :postage_id, Prefecture.all, :id, :name, prompt: "選択して下さい"
            %svg{width: "24", height: "24", viewBox: "0 0 24 24"}
              %path{d: "M12,15.66a1.73,1.73,0,0,1-1.2-.49L5.21,9.54a.7.7,0,0,1,1-1l5.62,5.62c.15.15.27.15.41,0L17.8,8.6a.71.71,0,0,1,1,0,.69.69,0,0,1,0,1l-5.57,5.58A1.71,1.71,0,0,1,12,15.66Z"}
        .formGroup
          .formLabel
            %label
              配送までの日数
            %span.tag.must
              必須
          .select
            = f.collection_select :shipping_day_id, ShippingDay.all, :id, :name, prompt: "選択して下さい"
            %svg{width: "24", height: "24", viewBox: "0 0 24 24"}
              %path{d: "M12,15.66a1.73,1.73,0,0,1-1.2-.49L5.21,9.54a.7.7,0,0,1,1-1l5.62,5.62c.15.15.27.15.41,0L17.8,8.6a.71.71,0,0,1,1,0,.69.69,0,0,1,0,1l-5.57,5.58A1.71,1.71,0,0,1,12,15.66Z"}
      %hr
      .block
        %p.title
          価格（¥300~9,999,999)
        .formGroup
          .price
            .result-price
              .formLabel.price-label
                %label
                  販売価格
                %span.tag.must.tag-price
                  必須
              %p.yen
                ¥
              .input-price
                = f.text_field :price
                
            .result-price
              販売手数料 (10%)
            %hr
            .result-price
              販売利益
          .pushbutton
            %button{type: "submit", class: 'submit button'}
              更新する
            %a.return.button{href: "/"}
              もどる
          %p.caution
            禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。

app/views/items/new.html.haml
.wrapper
  = render "new"

app/views/items/purchase.html.haml
.single-container
  
  .single-header
    = image_tag "logo.png", size: "185x49", alt: "test"

  .main
    .main__buy-content
      .main__buy-header
        購入内容の確認
      .main__buy-item
        .main__item-box
          = image_tag @item.images[0].image_url.url class:"main__item-image"
          .main__item-detail
            .buy__name
              = @item.name
            .buy__price
              %span 
                = "￥ #{@item.price}円"
              %span.item-sipping-fee (税込) 
              = @item.shippingpayer.name
      .main__btm
        .main__price
          .main__price-row
            .main__price-cell-lavel
              支払金額
            .main__price-cell
              = "￥ #{@item.price}円"
        .main__point
          =check_box_tag :check1  ,class:"main__check"
          %span  ポイントを使用 (所持ポイント: P --- )
        .main__user-info
          .main__payment
            支払方法
          = link_to new_credit_path(@item), class: "main__contents-top" do
            = icon('fas', 'plus-circle') 
            %span 登録してください
        .main__user
          .main__delivery
            .main__flex
              .main__left
                配送先
              = link_to "#", class: "main__contents-btm" do
                変更する
            .main__info
              %P〒210-1010
              %br 千葉県 市原市 八幡北町 1-1-10
              %br 薮田 貴文
        .main__btn
          - if user_signed_in? && current_user.id != @item.user_id 
            -if @default_card_information.blank?
              = link_to 'クレジットカード登録へ', new_credit_path(@item), class: "credit"
            - else
              = form_tag(action: :pay, method: :post) do
                %button 購入する
  .footer1
    .footer1__nav
      = link_to "#", class: "footer1__terms" do
        プライバシーポリシー
      = link_to "#", class: "footer1__terms" do
        メルカリ利用規約
      = link_to "#", class: "footer1__terms" do
        特定商取引に関する表記
    .footer1__logo
      = link_to root_path, class: "footer__image" do
        = image_tag "logo-white.png", size: "185x49", alt: "test"
    .footer1__copyright
      ©︎ Furima,Inc.

app/views/items/show.html.haml
= render partial: '/temple/header'
.itemContainer
  .itemName
    = @item.name
  .imageBox
    .imageBox__mainImage
      = image_tag @item.images[0].image_url.url, class: "mainImage"
    .imageBox__subImageBox
      - if (@item.images.length != 1)
        - @item.images.first(5).each do |image| 
          = image_tag image.image_url.url ,class:"image-item"

  .price
    = number_to_currency(@item.price, unit: "￥", format: "%u %n")
  %p.taxPostageIncluded （税込)
  .description
    = @item.description
       
        
  .itemMainContent__info
    .infoTable
      %table
        %tr.seller
          %th
            出品者
          %td
            = @item.user.nickname
        %tr.category
          %th
            カテゴリー
          %td
            %p.category__position= @category.name
            %p.arrow= @parents.name
            %br
            %p.arrow= @item.category.name

        %tr
          %th
            ブランド
          %td
            
        %tr
          %th
            商品状態
          %td
            = @item.condition.name

        %tr
          %th
            配送料の負担
          %td
            = @item.shippingpayer.name
        %tr
          %th
            配送日の目安
          %td
            = @item.shipping_day.name

  
  - if user_signed_in? && current_user.id != @item.user_id 
    %ur
      %li.detail-btn= link_to '購入確認画面へ', purchase_item_path(@item), class: "edit-btn"
      %a{href: "/"}
        ホームに戻る
  - if user_signed_in? && current_user.id == @item.user_id
    %ur
      %li.detail-btn= link_to '削除', item_path(@item), method: :delete, class: "destroy-btn", data: {confirm: "削除します。本当によろしいですか？"}
      %br
      %li.detail-btn= link_to '編集', edit_item_path(@item), class: "edit-btn"
      %a{href: "/"}
        ホームに戻る

= render partial: '/temple/footer'
  